### ISSUE TITLE
problems recreating

### ISSUE THREAD

**Issue by ngmisl** [farcasterxyz/redirect-frame#1]
Hi,

forked the exact same code, only changed links to my vercel url - deployment works fine. but when I try to use it as frame it's 404ing me... any idea?

**Comment by humanagent** [comment]
Same thing happened. Also using this particular repo and link
![CleanShot 2024-02-01 at 14 18 01@2x](https://github.com/farcasterxyz/redirect-frame/assets/1447073/85d42cde-5418-4564-84bf-78e55081a562)
